name: Python package
on: push
jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Running setup and testing cast.py on pipenv shell
      run: .github/build-binary.sh

    - uses: actions/upload-artifact@v2
      with:
          name: Creating artifacts
          path: code/dist/cast
